# Project-wide Gradle settings.

# Disable Gradle Configuration Cache (causes issues with some plugins)
org.gradle.configuration-cache=false

# Use AndroidX libraries
android.useAndroidX=true

# Kotlin DSL
org.gradle.kotlin.dsl.allWarningsAsErrors=false

# JVM Args
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
