# Project-wide Gradle settings.

# Enables Gradle Configuration Cache
org.gradle.configuration-cache=true

# Use AndroidX libraries
android.useAndroidX=true

# Kotlin DSL
org.gradle.kotlin.dsl.allWarningsAsErrors=false

# JVM Args
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8

# Enable BuildConfig generation
android.defaults.buildfeatures.buildconfig=true
